using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NetIde.Shell.Interop
{
    public enum NiTextMarkerHatchStyle
    {
        Default,
        Horizontal,
        Min,
        Vertical,
        ForwardDiagonal,
        BackwardDiagonal,
        Cross,
        LargeGrid,
        Max,
        DiagonalCross,
        Percent05,
        Percent10,
        Percent20,
        Percent25,
        Percent30,
        Percent40,
        Percent50,
        Percent60,
        Percent70,
        Percent75,
        Percent80,
        Percent90,
        LightDownwardDiagonal,
        LightUpwardDiagonal,
        DarkDownwardDiagonal,
        DarkUpwardDiagonal,
        WideDownwardDiagonal,
        WideUpwardDiagonal,
        LightVertical,
        LightHorizontal,
        NarrowVertical,
        NarrowHorizontal,
        DarkVertical,
        DarkHorizontal,
        DashedDownwardDiagonal,
        DashedUpwardDiagonal,
        DashedHorizontal,
        DashedVertical,
        SmallConfetti,
        LargeConfetti,
        ZigZag,
        Wave,
        DiagonalBrick,
        HorizontalBrick,
        Weave,
        Plaid,
        Divot,
        DottedGrid,
        DottedDiamond,
        Shingle,
        Trellis,
        Sphere,
        SmallGrid,
        SmallCheckerBoard,
        LargeCheckerBoard,
        OutlinedDiamond,
        SolidDiamond
    }
}
