//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetIde.Setup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetIde.Setup.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All components are already at their latest version..
        /// </summary>
        internal static string AllPackagesUpToDate {
            get {
                return ResourceManager.GetString("AllPackagesUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit {0}?.
        /// </summary>
        internal static string AreYouSureQuit {
            get {
                return ResourceManager.GetString("AreYouSureQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setup cannot be aborted at this moment.
        /// </summary>
        internal static string CannotAbortSetup {
            get {
                return ResourceManager.GetString("CannotAbortSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download metadata for package &apos;{0}&apos;.
        /// </summary>
        internal static string CannotDownloadPackageMetadata {
            get {
                return ResourceManager.GetString("CannotDownloadPackageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not yet installed on this system. Please run the setup for {0} and then re-run this setup..
        /// </summary>
        internal static string ContextNotInstalled {
            get {
                return ResourceManager.GetString("ContextNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating context &apos;{0}&apos;.
        /// </summary>
        internal static string CreatingContext {
            get {
                return ResourceManager.GetString("CreatingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating desktop shortcut.
        /// </summary>
        internal static string CreatingDesktopShortcut {
            get {
                return ResourceManager.GetString("CreatingDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating start menu shortcut.
        /// </summary>
        internal static string CreatingStartMenuShortcut {
            get {
                return ResourceManager.GetString("CreatingStartMenuShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading package &apos;{0}&apos;.
        /// </summary>
        internal static string DownloadingPackage {
            get {
                return ResourceManager.GetString("DownloadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net IDE Package Setup v{0}.
        /// </summary>
        internal static string FooterSetupLine {
            get {
                return ResourceManager.GetString("FooterSetupLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing the {0} Setup Wizard.
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been installed on your computer..
        /// </summary>
        internal static string InstallCompleteSubText {
            get {
                return ResourceManager.GetString("InstallCompleteSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the components before installing {0}..
        /// </summary>
        internal static string InstallComponentsConfirm {
            get {
                return ResourceManager.GetString("InstallComponentsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following components will be installed. Review the selected components and click Next to begin the installation..
        /// </summary>
        internal static string InstallComponentsConfirmSubText {
            get {
                return ResourceManager.GetString("InstallComponentsConfirmSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package &apos;{0}&apos;.
        /// </summary>
        internal static string InstallingPackage {
            get {
                return ResourceManager.GetString("InstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {0} is being installed..
        /// </summary>
        internal static string InstallingSubText {
            get {
                return ResourceManager.GetString("InstallingSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {0} Setup Wizard.
        /// </summary>
        internal static string InstallWelcome {
            get {
                return ResourceManager.GetString("InstallWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will guide you through the installation of {0}..
        /// </summary>
        internal static string InstallWelcomeSubText {
            get {
                return ResourceManager.GetString("InstallWelcomeSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration is invalid.
        /// </summary>
        internal static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net IDE Package Setup.
        /// </summary>
        internal static string NetIdePackageSetup {
            get {
                return ResourceManager.GetString("NetIdePackageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving dependencies.
        /// </summary>
        internal static string ResolvingDependencies {
            get {
                return ResourceManager.GetString("ResolvingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected situation has occurred:
        ///
        ///{0}.
        /// </summary>
        internal static string UnexpectedSituation {
            get {
                return ResourceManager.GetString("UnexpectedSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing the {0} Update Wizard.
        /// </summary>
        internal static string UpdateComplete {
            get {
                return ResourceManager.GetString("UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated to its latest version..
        /// </summary>
        internal static string UpdateCompleteSubText {
            get {
                return ResourceManager.GetString("UpdateCompleteSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the components before updating {0}..
        /// </summary>
        internal static string UpdateComponentsConfirm {
            get {
                return ResourceManager.GetString("UpdateComponentsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following components will be updated. Review the selected components and click Next to begin the update process..
        /// </summary>
        internal static string UpdateComponentsConfirmSubText {
            get {
                return ResourceManager.GetString("UpdateComponentsConfirmSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {0} Update Wizard.
        /// </summary>
        internal static string UpdateWelcome {
            get {
                return ResourceManager.GetString("UpdateWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will guide you through the update process of {0}..
        /// </summary>
        internal static string UpdateWelcomeSubText {
            get {
                return ResourceManager.GetString("UpdateWelcomeSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {0} is being updated..
        /// </summary>
        internal static string UpdatingSubText {
            get {
                return ResourceManager.GetString("UpdatingSubText", resourceCulture);
            }
        }
    }
}
