//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetIde.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetIde.Core.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary file differs..
        /// </summary>
        internal static string BinaryFileSummary {
            get {
                return ResourceManager.GetString("BinaryFileSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff Viewer.
        /// </summary>
        internal static string DiffViewerName {
            get {
                return ResourceManager.GetString("DiffViewerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} bytes.
        /// </summary>
        internal static string FileSizeBytes {
            get {
                return ResourceManager.GetString("FileSizeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.0} GB.
        /// </summary>
        internal static string FileSizeGigaBytes {
            get {
                return ResourceManager.GetString("FileSizeGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.0} KB.
        /// </summary>
        internal static string FileSizeKiloBytes {
            get {
                return ResourceManager.GetString("FileSizeKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.0} MB.
        /// </summary>
        internal static string FileSizeMegaBytes {
            get {
                return ResourceManager.GetString("FileSizeMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string FontBold {
            get {
                return ResourceManager.GetString("FontBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string FontItalic {
            get {
                return ResourceManager.GetString("FontItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string FontRegular {
            get {
                return ResourceManager.GetString("FontRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string Fonts {
            get {
                return ResourceManager.GetString("Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikeout.
        /// </summary>
        internal static string FontStrikeout {
            get {
                return ResourceManager.GetString("FontStrikeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string FontUnderline {
            get {
                return ResourceManager.GetString("FontUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Prerelease.
        /// </summary>
        internal static string IncludePrerelease {
            get {
                return ResourceManager.GetString("IncludePrerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last published.
        /// </summary>
        internal static string LastPublished {
            get {
                return ResourceManager.GetString("LastPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close A&amp;ll Documents.
        /// </summary>
        internal static string MenuCloseAllDocuments {
            get {
                return ResourceManager.GetString("MenuCloseAllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;lose.
        /// </summary>
        internal static string MenuFileClose {
            get {
                return ResourceManager.GetString("MenuFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Pro&amp;ject.
        /// </summary>
        internal static string MenuFileCloseProject {
            get {
                return ResourceManager.GetString("MenuFileCloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New P&amp;roject.
        /// </summary>
        internal static string MenuFileNewProject {
            get {
                return ResourceManager.GetString("MenuFileNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Project.
        /// </summary>
        internal static string MenuFileOpenProject {
            get {
                return ResourceManager.GetString("MenuFileOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa&amp;ve All.
        /// </summary>
        internal static string MenuFileSaveAll {
            get {
                return ResourceManager.GetString("MenuFileSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As.
        /// </summary>
        internal static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options....
        /// </summary>
        internal static string MenuToolsOptions {
            get {
                return ResourceManager.GetString("MenuToolsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions and Updates....
        /// </summary>
        internal static string MenuToolsPackageManagement {
            get {
                return ResourceManager.GetString("MenuToolsPackageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Window.
        /// </summary>
        internal static string MenuWindow {
            get {
                return ResourceManager.GetString("MenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Downloads.
        /// </summary>
        internal static string MostDownloads {
            get {
                return ResourceManager.GetString("MostDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Ascending.
        /// </summary>
        internal static string NameAscending {
            get {
                return ResourceManager.GetString("NameAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Descending.
        /// </summary>
        internal static string NameDescending {
            get {
                return ResourceManager.GetString("NameDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages are available..
        /// </summary>
        internal static string NoPackagesAvailable {
            get {
                return ResourceManager.GetString("NoPackagesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages are installed..
        /// </summary>
        internal static string NoPackagesInstalled {
            get {
                return ResourceManager.GetString("NoPackagesInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No package updates are available..
        /// </summary>
        internal static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net IDE Core.
        /// </summary>
        internal static string PackageDescription {
            get {
                return ResourceManager.GetString("PackageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        internal static string PlainText {
            get {
                return ResourceManager.GetString("PlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Explorer.
        /// </summary>
        internal static string ProjectExplorer {
            get {
                return ResourceManager.GetString("ProjectExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Date.
        /// </summary>
        internal static string PublishedDate {
            get {
                return ResourceManager.GetString("PublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable Only.
        /// </summary>
        internal static string StableOnly {
            get {
                return ResourceManager.GetString("StableOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor.
        /// </summary>
        internal static string TextEditorName {
            get {
                return ResourceManager.GetString("TextEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
