//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetIde {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetIde.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current operation cannot be cancelled..
        /// </summary>
        internal static string CannotCancelOperation {
            get {
                return ResourceManager.GetString("CannotCancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create project.
        /// </summary>
        internal static string CannotCreateProject {
            get {
                return ResourceManager.GetString("CannotCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find command &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindCommand {
            get {
                return ResourceManager.GetString("CannotFindCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find command bar &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindCommandBar {
            get {
                return ResourceManager.GetString("CannotFindCommandBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find command group &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindCommandGroup {
            get {
                return ResourceManager.GetString("CannotFindCommandGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find project factory.
        /// </summary>
        internal static string CannotFindProjectFactory {
            get {
                return ResourceManager.GetString("CannotFindProjectFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the file NiContext.xml. Your installation may be corrupt..
        /// </summary>
        internal static string CannotLoadContext {
            get {
                return ResourceManager.GetString("CannotLoadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open project.
        /// </summary>
        internal static string CannotOpenProject {
            get {
                return ResourceManager.GetString("CannotOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process switch &apos;{0}&apos;..
        /// </summary>
        internal static string CannotProcessSwitch {
            get {
                return ResourceManager.GetString("CannotProcessSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo boxes are only supported on toolbars.
        /// </summary>
        internal static string ComboBoxNotSupported {
            get {
                return ResourceManager.GetString("ComboBoxNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command bar has already been registered.
        /// </summary>
        internal static string CommandBarAlreadyRegistered {
            get {
                return ResourceManager.GetString("CommandBarAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NetIde.Package.Core package is missing..
        /// </summary>
        internal static string CorePackageMissing {
            get {
                return ResourceManager.GetString("CorePackageMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse keys &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotParseKeys {
            get {
                return ResourceManager.GetString("CouldNotParseKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        internal static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document is registered for the provided cookie.
        /// </summary>
        internal static string DocumentNotRegistered {
            get {
                return ResourceManager.GetString("DocumentNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading package {0}.
        /// </summary>
        internal static string DownloadingPackage {
            get {
                return ResourceManager.GetString("DownloadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor factory has already been registered.
        /// </summary>
        internal static string EditorFactoryAlreadyRegistered {
            get {
                return ResourceManager.GetString("EditorFactoryAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        internal static string InsertModeInsert {
            get {
                return ResourceManager.GetString("InsertModeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVR.
        /// </summary>
        internal static string InsertModeOverwrite {
            get {
                return ResourceManager.GetString("InsertModeOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package {0}.
        /// </summary>
        internal static string InstallingPackage {
            get {
                return ResourceManager.GetString("InstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource name &apos;{0}&apos; is invalid or could not be found..
        /// </summary>
        internal static string InvalidBitmapResource {
            get {
                return ResourceManager.GetString("InvalidBitmapResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandBar style must be Menu or ToolStrip.
        /// </summary>
        internal static string InvalidCommandBarStyle {
            get {
                return ResourceManager.GetString("InvalidCommandBarStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package manifest &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string InvalidPackageManifest {
            get {
                return ResourceManager.GetString("InvalidPackageManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Details.
        /// </summary>
        internal static string LessDetails {
            get {
                return ResourceManager.GetString("LessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu is not a popup menu.
        /// </summary>
        internal static string MenuIsNotPopup {
            get {
                return ResourceManager.GetString("MenuIsNotPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Details.
        /// </summary>
        internal static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net IDE.
        /// </summary>
        internal static string NetIde {
            get {
                return ResourceManager.GetString("NetIde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource file does not contain a NiResources resource.
        /// </summary>
        internal static string NiResourcesMissing {
            get {
                return ResourceManager.GetString("NiResourcesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close the project until all open documents have been closed.
        /// </summary>
        internal static string OpenDocumentsPresent {
            get {
                return ResourceManager.GetString("OpenDocumentsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        internal static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry point &apos;{0}&apos; is invalid; must be of format &apos;&lt;assembly&gt;, &lt;type&gt;&apos;.
        /// </summary>
        internal static string PackageEntryPointInvalid {
            get {
                return ResourceManager.GetString("PackageEntryPointInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load and initialize package &apos;{0}&apos;.
        /// </summary>
        internal static string PackageInitializationFailed {
            get {
                return ResourceManager.GetString("PackageInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify either the editor guid or document.
        /// </summary>
        internal static string SpecifyEitherDocumentOrEditorGuid {
            get {
                return ResourceManager.GetString("SpecifyEitherDocumentOrEditorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch {0}.
        /// </summary>
        internal static string StatusBarCharIndex {
            get {
                return ResourceManager.GetString("StatusBarCharIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusBarDefaultStatus {
            get {
                return ResourceManager.GetString("StatusBarDefaultStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col {0}.
        /// </summary>
        internal static string StatusBarIndex {
            get {
                return ResourceManager.GetString("StatusBarIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln {0}.
        /// </summary>
        internal static string StatusBarLine {
            get {
                return ResourceManager.GetString("StatusBarLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing package {0}.
        /// </summary>
        internal static string UninstallingPackage {
            get {
                return ResourceManager.GetString("UninstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed: {0}.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating package {0}.
        /// </summary>
        internal static string UpdatingPackage {
            get {
                return ResourceManager.GetString("UpdatingPackage", resourceCulture);
            }
        }
    }
}
