//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetIde {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NeutralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NeutralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetIde.NeutralResources", typeof(NeutralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find command &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindCommand {
            get {
                return ResourceManager.GetString("CannotFindCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find command bar &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindCommandBar {
            get {
                return ResourceManager.GetString("CannotFindCommandBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find command group &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindCommandGroup {
            get {
                return ResourceManager.GetString("CannotFindCommandGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find project factory.
        /// </summary>
        internal static string CannotFindProjectFactory {
            get {
                return ResourceManager.GetString("CannotFindProjectFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo boxes are only supported in menus.
        /// </summary>
        internal static string ComboBoxNotSupported {
            get {
                return ResourceManager.GetString("ComboBoxNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command bar has already been registered.
        /// </summary>
        internal static string CommandBarAlreadyRegistered {
            get {
                return ResourceManager.GetString("CommandBarAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document is registered for the provided cookie.
        /// </summary>
        internal static string DocumentNotRegistered {
            get {
                return ResourceManager.GetString("DocumentNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor factory has already been registered.
        /// </summary>
        internal static string EditorFactoryAlreadyRegistered {
            get {
                return ResourceManager.GetString("EditorFactoryAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource name &apos;{0}&apos; is invalid or could not be found..
        /// </summary>
        internal static string InvalidBitmapResource {
            get {
                return ResourceManager.GetString("InvalidBitmapResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandBar style must be Menu or ToolStrip.
        /// </summary>
        internal static string InvalidCommandBarStyle {
            get {
                return ResourceManager.GetString("InvalidCommandBarStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels are not supported in menus.
        /// </summary>
        internal static string LabelNotSupported {
            get {
                return ResourceManager.GetString("LabelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu is not a popup menu.
        /// </summary>
        internal static string MenuIsNotPopup {
            get {
                return ResourceManager.GetString("MenuIsNotPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry point &apos;{0}&apos; is invalid; must be of format &apos;&lt;assembly&gt;, &lt;type&gt;&apos;.
        /// </summary>
        internal static string PackageEntryPointInvalid {
            get {
                return ResourceManager.GetString("PackageEntryPointInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify either the editor guid or document.
        /// </summary>
        internal static string SpecifyEitherDocumentOrEditorGuid {
            get {
                return ResourceManager.GetString("SpecifyEitherDocumentOrEditorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text boxes are not supported in menus.
        /// </summary>
        internal static string TextBoxNotSupported {
            get {
                return ResourceManager.GetString("TextBoxNotSupported", resourceCulture);
            }
        }
    }
}
